---
version: "2.0"

services:
  uploader:
    image: mbbrains/drive-uploader
    expose:
      - port: 80
        as: 80
        to:
          - global: true

profiles:
  compute:
    uploader:
      resources:
        cpu:
          units: 4
        memory:
          size: 2048Mi
        storage:
          size: 2048MI
  placement:
    dcloud:
      attributes:
        host: akash
      pricing:
        uploader:
          denom: uakt
          amount: 100

deployment:
  uploader:
    dcloud:
      profile: uploader
      count: 1
